services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - amr

  amr:
    container_name: amr
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - PORT=8000
      - DEBUG=False
    depends_on:
      - redis
    networks:
      - amr

networks:
  amr:
    driver: bridge

volumes:
  redis_data:
    driver: local
