services:
  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: amr_app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - amr

  amr:
    container_name: amr
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    environment:
      - POSTGRES_URL=dbname=amr_app user=postgres password=postgres host=postgres port=5432
      - DEBUG=False
      - PORT=80
    networks:
      - amr
    depends_on:
      - postgres

volumes:
  postgres_data:
    driver: local

networks:
  amr:
    driver: bridge
